### ISSUE TITLE
PyTEAL Imports

### ISSUE THREAD

**Issue by jpramos-me** [gradual-verification/gradual-TEAL#2]
As shown in https://github.com/gradual-verification/gradual-TEAL/commit/4cae2042550d683967171344bcaccde599c344b7, we have working single imports! However, there are a few things to address...

- [ ] Throughout the transformer and IR, the `isLibrary` boolean check for valid libraries is hardcoded/removed. This is because gvc0 checks for local libraries and doesn't really make use of downloaded ones. We basically only care about pyTEAL for the basic examples, but we'll definitely have to re-integrate the checks for local libraries to support a module system!
- [x] Currently, gvc0 imports require either `"lib"` or `<lib>`, we want to remove these indicators for PyTEAL 
- [x] Compound imports of the style `from . import .` still have yet to be implemented. This is because in gvc0 they use a single `ResolvedDependencies` class for resolving libraries, whereas we have two classes (one for single imports and another for composed). Although this seems to be the standard ([Python parser example here](https://github.com/com-lihaoyi/fastparse/blob/8e8571b5dfb92fe92a5b081677e923836a3bffb9/pythonparse/src/pythonparse/Ast.scala#L47)) we might have to think of combining them or adding extra logic in the resolver for resolving both imports.
- [x] Due to type casting issues, we can only import a single library at a time. Python supports single line multi-imports, for which the logic is already implemented [here](https://github.com/gradual-verification/gradual-TEAL/blob/4cae2042550d683967171344bcaccde599c344b7/src/main/scala/gvteal/parser/Definitions.scala#L15). We just have to fix typecasting from `String -> StringExpression` or find a way to convert the `Seq[StringExpression]` created by `libraryPath.rep(0, ",")` into a single `StringExpression` without converting to `String` first. This would require a helper function.

**Comment by janpaulpl** [comment]
Most of this solved under https://github.com/gradual-verification/gradual-TEAL/commit/65f15b53e83234f4e182b6a31fb43fcd56d99976, closing `isLibrary` check as not needed.
